[workspace]
authors = ["Hamid Adesokan <aadehamid@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojoWithPixi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
